**Nombre:** Alejandro Casado Figueredo
\
**Github:** https://github.com/alexcefe02


## 1. Introducción

En la actualidad, la ciencia de datos y la computación científica se han convertido en pilares fundamentales de numerosas disciplinas, desde la ingeniería hasta la investigación social. En este contexto, Python se ha consolidado como uno de los lenguajes de programación más utilizados gracias a su simplicidad, legibilidad y enorme ecosistema de bibliotecas especializadas.

Entre estas bibliotecas, **NumPy** (Numerical Python) ocupa una posición central. Esta librería proporciona estructuras de datos eficientes y funciones especializadas para realizar cálculos numéricos de forma rápida y optimizada. En particular, su estructura de datos principal, el `ndarray` (N-dimensional array), permite manipular grandes volúmenes de datos numéricos de manera eficiente, aprovechando operaciones vectorizadas y técnicas avanzadas de procesamiento.

El presente trabajo parte del análisis del capítulo "Empowering Scientific Computing and Data Manipulation With Numerical Python (NumPy)", incluido en una obra colectiva publicada por IGI Global. Este artículo profundiza en el papel que desempeña NumPy dentro del ecosistema científico de Python, explicando conceptos clave como los tipos de datos que maneja, las operaciones básicas y avanzadas que permite realizar, y su interoperabilidad con otros lenguajes como C o C++.

El objetivo de este notebook es sintetizar los principales conceptos desarrollados en dicho artículo y acompañarlos de ejemplos prácticos en Python, con el fin de ilustrar cómo NumPy puede empoderar el procesamiento científico y la manipulación de datos en entornos reales.

---

## 2. Resumen del artículo

El capítulo titulado *"Empowering Scientific Computing and Data Manipulation With Numerical Python (NumPy)"* examina a fondo el rol de NumPy en el ecosistema de Python para la computación científica y el análisis de datos. El artículo, escrito por Tesfaye Fufa Gedefa, Galety Mohammed Gouse y Garamu Tilahun Iticha (2023), destaca cómo NumPy se ha convertido en la piedra angular para el desarrollo de aplicaciones numéricas y científicas, proporcionando estructuras de datos eficientes y herramientas robustas para el tratamiento de datos de múltiples dimensiones.

### Principales ideas desarrolladas:

#### I. El objeto `ndarray`
El núcleo de NumPy es el objeto `ndarray`, una estructura de datos N-dimensional que permite representar y manipular arrays de forma eficiente. Este objeto admite operaciones vectorizadas, es decir, operaciones que se aplican a colecciones completas de datos sin necesidad de bucles explícitos.

#### II. Tipos de datos en NumPy
NumPy admite distintos tipos de datos numéricos: enteros sin signo (`uint8`, `uint16`), enteros con signo (`int8`, `int16`), números en coma flotante (`float32`, `float64`), números complejos, y también tipos personalizados. A través del `dtype`, los arrays pueden configurarse para ser altamente eficientes en memoria y procesamiento.

#### III. Operaciones vectorizadas y rendimiento
Las operaciones aritméticas básicas (suma, resta, multiplicación, división), así como operaciones más complejas (algebra lineal, transformadas, estadísticas), están optimizadas para ejecutarse rápidamente gracias a la asignación contigua de memoria y el uso de instrucciones SIMD (Single Instruction Multiple Data).

#### IV. Diferencias entre listas y arrays
A diferencia de las listas de Python, los arrays de NumPy:
- Ocupan menos memoria.
- Permiten procesamiento numérico más rápido.
- Son homogéneos (todos sus elementos tienen el mismo tipo de dato).
- Permiten operaciones matemáticas nativas sin necesidad de iteración explícita.

#### V. Técnicas clave: slicing, broadcasting, reshaping
El artículo explica conceptos avanzados como:
- **Slicing**: selección eficiente de subconjuntos de arrays.
- **Broadcasting**: operaciones entre arrays de diferentes formas, mediante reglas internas que "extienden" sus dimensiones.
- **Reshaping**: transformación de la forma (shape) del array sin alterar sus datos.

#### VI. Funciones estadísticas y algebraicas
NumPy proporciona funciones para:
- Análisis estadístico (mínimo, máximo, media, desviación estándar...).
- Álgebra lineal (producto de matrices, determinantes, sistemas de ecuaciones...).
- Trigonometría, redondeo, búsqueda y ordenación.

#### VII. Aplicaciones e interoperabilidad
NumPy es utilizado ampliamente en ciencia de datos, ingeniería, redes complejas, machine learning y big data. Además, se integra fácilmente con otros lenguajes como C/C++ y con bibliotecas como Pandas, SciPy o TensorFlow.


---


En resumen, el artículo resalta el potencial de NumPy como base tecnológica para cualquier aplicación de computación numérica en Python, por su rendimiento, simplicidad sintáctica y extensibilidad. A lo largo del notebook se mostrarán ejemplos concretos que ilustran estos conceptos.


## 3. Instalación e Importación

Antes de utilizar las funcionalidades de NumPy, es necesario asegurarse de que la biblioteca esté instalada en el entorno de Python. NumPy se puede instalar fácilmente desde el gestor de paquetes `pip` o mediante entornos de distribución como `conda`.

Una vez instalada, se importa la librería en el código, normalmente bajo el alias estándar `np`, lo cual es una convención ampliamente utilizada por la comunidad científica y de desarrollo.

Este alias permite escribir el código de forma más legible y concisa, por ejemplo: `np.array()` en lugar de `numpy.array()`.


In [4]:
#  Instalación de NumPy
# !pip install numpy       # Si usas pip
# !conda install numpy     # Si usas conda

#  Importación de la librería con alias estándar
import numpy as np

#  Verificación de versión instalada
print("Versión de NumPy:", np.__version__)

Versión de NumPy: 1.26.4


## 4. Tipos de datos en NumpPy

NumPy trabaja principalmente con un tipo de estructura de datos llamada `ndarray` (N-dimensional array), que puede representar desde un número escalar hasta un tensor de múltiples dimensiones. Los tipos más comunes que podemos encontrar son:

- **Escalar (0D)**  
  Un único valor numérico, sin dimensiones.

- **Vector (1D)**  
  Una lista unidimensional de valores.

- **Matriz (2D)**  
  Una tabla de valores con filas y columnas (array bidimensional).

- **Tensor (nD, n > 2)**  
  Una estructura de datos multidimensional (3D o más), muy útil en aplicaciones científicas y de inteligencia artificial.

A continuación se muestran ejemplos en Python para cada uno de estos tipos utilizando la función `np.array()`.


In [5]:
# Escalar: una sola cantidad (0 dimensiones)
escalar = np.array(7)
print("Escalar:", escalar)
print("Dimensiones:", escalar.ndim)
print("Forma:", escalar.shape)

Escalar: 7
Dimensiones: 0
Forma: ()


In [6]:
# Vector: una lista de valores (1D)
vector = np.array([10, 20, 30])
print("Vector:", vector)
print("Dimensiones:", vector.ndim)
print("Forma:", vector.shape)


Vector: [10 20 30]
Dimensiones: 1
Forma: (3,)


In [4]:
# Matriz: array bidimensional (2D)
matriz = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Matriz:\n", matriz)
print("Dimensiones:", matriz.ndim)
print("Forma:", matriz.shape)


Matriz:
 [[1 2 3]
 [4 5 6]]
Dimensiones: 2
Forma: (2, 3)


In [7]:
# Tensor: array tridimensional (3D)
tensor = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print("Tensor:\n", tensor)
print("Dimensiones:", tensor.ndim)
print("Forma:", tensor.shape)


Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimensiones: 3
Forma: (2, 2, 2)


## 5. Operaciones con Arrays

NumPy permite realizar operaciones matemáticas y estructurales sobre arrays de forma sencilla, rápida y vectorizada, es decir, sin necesidad de usar bucles.

A continuación se presentan algunas de las operaciones más comunes:

- **Operaciones aritméticas**: suma, resta, multiplicación, división, etc.
- **Transposición de arrays**: invertir filas por columnas.
- **Concatenación y división**: unir o dividir arrays.
- **Redimensionamiento (reshape)**: cambiar la forma del array sin alterar los datos.


In [8]:
# Creamos dos arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Operaciones elemento a elemento
print("Suma:", a + b)
print("Resta:", a - b)
print("Multiplicación:", a * b)
print("División:", a / b)


Suma: [5 7 9]
Resta: [-3 -3 -3]
Multiplicación: [ 4 10 18]
División: [0.25 0.4  0.5 ]


In [10]:
# Matriz 2D
matriz = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Transponer (intercambiar filas y columnas)
transpuesta = matriz.T

print("Matriz original:\n", matriz)
print("Transpuesta:\n", transpuesta)


Matriz original:
 [[1 2 3]
 [4 5 6]]
Transpuesta:
 [[1 4]
 [2 5]
 [3 6]]


In [9]:
# Concatenar dos vectores horizontalmente
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
concat = np.concatenate([x, y])

print("Concatenación:", concat)


Concatenación: [1 2 3 4 5 6]


In [10]:
# Dividir un array en tres partes iguales
z = np.array([10, 20, 30, 40, 50, 60])
split = np.split(z, 3)

print("División en partes:")
for i, part in enumerate(split):
    print(f"Parte {i+1}:", part)


División en partes:
Parte 1: [10 20]
Parte 2: [30 40]
Parte 3: [50 60]


In [7]:
# Reshape de un array de 1D a 2D
original = np.array([1, 2, 3, 4, 5, 6])
reshape = original.reshape((2, 3))

print("Array original:", original)
print("Reshape a 2x3:\n", reshape)


Array original: [1 2 3 4 5 6]
Reshape a 2x3:
 [[1 2 3]
 [4 5 6]]


## 6. Slicing, Indexing y Broadcasting

NumPy proporciona herramientas avanzadas para acceder, modificar y operar sobre subconjuntos de arrays de forma eficiente. Estas son claves para trabajar con datos a gran escala.

- **Indexing**: acceder a elementos concretos de un array mediante índices.
- **Slicing**: seleccionar rangos de elementos utilizando la notación `[inicio:fin:paso]`.
- **Broadcasting**: permite realizar operaciones aritméticas entre arrays de distintas formas (dimensiones), siempre que sean compatibles bajo las reglas de broadcasting.

Estas capacidades permiten escribir código más conciso, rápido y expresivo.

In [11]:
# Crear un array 2D
matriz = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

# Acceder al elemento de la fila 1, columna 2
print("Elemento [1,2]:", matriz[1, 2])  # Output: 60


Elemento [1,2]: 60


In [12]:
# Seleccionar un subconjunto de filas y columnas
submatriz = matriz[0:2, 1:]  # Filas 0-1, columnas 1-2
print("Submatriz con slicing:\n", submatriz)

# Slicing en 1D
vector = np.array([5, 10, 15, 20, 25, 30])
print("Segmento vector[1:5:2]:", vector[1:5:2])  # Output: [10 20]


Submatriz con slicing:
 [[20 30]
 [50 60]]
Segmento vector[1:5:2]: [10 20]


In [13]:
# Array 2D
a = np.array([[1, 2, 3],
              [4, 5, 6]])

# Vector 1D que se "extiende" automáticamente (broadcast)
b = np.array([10, 20, 30])

# Suma por filas (cada elemento de b se suma a una fila de a)
resultado = a + b

print("Resultado de broadcasting:\n", resultado)


Resultado de broadcasting:
 [[11 22 33]
 [14 25 36]]


In [14]:
# Multiplicación por escalar (broadcast implícito)
x = np.array([1, 2, 3, 4])
print("Multiplicación por escalar (2):", x * 2)

Multiplicación por escalar (2): [2 4 6 8]


## 7. Funciones especiales de Numpy

Además de operaciones básicas, NumPy proporciona una amplia gama de funciones especializadas para el cálculo matemático, estadístico y científico. A continuación se presentan algunas de las más relevantes:

- **Funciones trigonométricas**: cálculos con ángulos en radianes.
- **Funciones de redondeo**: aproximación de valores decimales.
- **Funciones estadísticas**: análisis de datos (mínimo, máximo, media, etc.).
- **Álgebra lineal**: operaciones con matrices, determinantes, autovalores, etc.

Estas funciones hacen de NumPy una herramienta clave en análisis numérico y modelado matemático.

In [15]:
# Ángulos en radianes
ángulos = np.array([0, np.pi/2, np.pi])

# Funciones trigonométricas
print("Seno:", np.sin(ángulos))
print("Coseno:", np.cos(ángulos))
print("Tangente:", np.tan(ángulos))


Seno: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Coseno: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Tangente: [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [16]:
# Array con decimales
valores = np.array([3.14159, 2.71828, 1.61803])

# Redondear a 2 decimales
print("Original:", valores)
print("Redondeado (2 decimales):", np.round(valores, 2))


Original: [3.14159 2.71828 1.61803]
Redondeado (2 decimales): [3.14 2.72 1.62]


In [17]:
# Datos simulados
datos = np.array([10, 20, 30, 40, 50])

print("Mínimo:", np.min(datos))
print("Máximo:", np.max(datos))
print("Media:", np.mean(datos))
print("Desviación estándar:", np.std(datos))


Mínimo: 10
Máximo: 50
Media: 30.0
Desviación estándar: 14.142135623730951


In [18]:
# Matriz 2x2
A = np.array([[3, 1],
              [2, 4]])

# Vector columna
b = np.array([9, 10])

# Resolver sistema lineal Ax = b
x = np.linalg.solve(A, b)
print("Solución del sistema Ax = b:", x)

# Determinante
print("Determinante de A:", np.linalg.det(A))

# Matriz inversa
print("Inversa de A:\n", np.linalg.inv(A))


Solución del sistema Ax = b: [2.6 1.2]
Determinante de A: 10.000000000000002
Inversa de A:
 [[ 0.4 -0.1]
 [-0.2  0.3]]


## 8. Diferencias listas y arrays

Aunque las listas de Python y los arrays de NumPy pueden parecer similares, existen diferencias clave que hacen que los arrays sean más eficientes y adecuados para el procesamiento numérico:

| Característica              | Lista de Python             | Array de NumPy                   |
|----------------------------|-----------------------------|----------------------------------|
| Tipos de datos             | Heterogéneos                | Homogéneos                       |
| Velocidad                  | Más lenta                   | Más rápida (vectorización)       |
| Consumo de memoria         | Mayor                       | Menor                            |
| Operaciones matemáticas    | Requiere bucles manuales    | Nativas y optimizadas            |
| Necesidad de importar      | No                          | Sí (`import numpy as np`)        |

**Conclusión:**  
Las listas son estructuras versátiles para datos heterogéneos y generales, mientras que los arrays de NumPy están optimizados para cálculos numéricos a gran escala, siendo mucho más rápidos y eficientes.

In [19]:
import numpy as np
import sys
import time

# Tamaño de muestra
n = 1_000_000

# Lista de Python
lista = list(range(n))

# Array de NumPy
array = np.arange(n)

# Memoria usada
print("Memoria ocupada por la lista:", sys.getsizeof(lista), "bytes")
print("Memoria ocupada por el array:", array.nbytes, "bytes")

# Suma: lista vs array
start = time.time()
lista_resultado = [x + 1 for x in lista]
print("Tiempo de suma con lista:", round(time.time() - start, 4), "s")

start = time.time()
array_resultado = array + 1
print("Tiempo de suma con array:", round(time.time() - start, 4), "s")

Memoria ocupada por la lista: 8000056 bytes
Memoria ocupada por el array: 4000000 bytes
Tiempo de suma con lista: 0.0589 s
Tiempo de suma con array: 0.001 s


## 9. Aplicación práctica

Una aplicación habitual en ciencia de datos es la **normalización**, que transforma un conjunto de datos para que sus valores estén en un rango específico (habitualmente entre 0 y 1). Esto permite mejorar la estabilidad numérica de los algoritmos y evita que una escala domine a otra.

### - Ejemplo: Normalización Min-Max

Dado un array de números enteros aleatorios, aplicaremos la fórmula:

    [X_{norm} = \frac{X - X_{min}}{X_{max} - X_{min}}]

Este proceso se realiza fácilmente gracias a la capacidad de operaciones vectorizadas de NumPy.

In [30]:
# Generar datos aleatorios
datos = np.random.randint(1, 1000, size=10)
print("Datos originales:", datos)

# Normalización min-max
normalizado = (datos - np.min(datos)) / (np.max(datos) - np.min(datos))
print("Datos normalizados:", normalizado)

Datos originales: [455 682 947 249 617 588 640 841 213 107]
Datos normalizados: [0.414 0.685 1.000 0.169 0.607 0.573 0.635 0.874 0.126 0.000]


## 10. Conclusiones

A lo largo de este trabajo se ha demostrado cómo **NumPy** constituye una herramienta clave para el desarrollo de aplicaciones de computación científica y análisis de datos en Python. Basándonos en el capítulo analizado y en los ejemplos prácticos presentados, pueden extraerse las siguientes conclusiones:

- **Eficiencia y rendimiento:** El uso de estructuras como `ndarray` permite realizar cálculos numéricos de forma mucho más rápida y eficiente que con estructuras nativas como las listas, gracias a la asignación contigua de memoria y a la vectorización de operaciones.

- **Versatilidad funcional:** NumPy proporciona un amplio abanico de funciones para realizar operaciones matemáticas, estadísticas, algebraicas, y de manipulación de datos multidimensionales (slicing, reshaping, broadcasting...).
- **Facilidad de uso y legibilidad:** La sintaxis clara y coherente, junto con las convenciones como `import numpy as np`, hacen que el código sea legible y fácil de mantener.
- **Interoperabilidad:** NumPy no solo es fundamental por sí solo, sino que actúa como base para otras bibliotecas clave del ecosistema científico de Python (Pandas, SciPy, Scikit-learn, etc.), e incluso se puede integrar con lenguajes como C o C++.
- **Aplicabilidad real:** Se han mostrado casos prácticos, como la normalización de datos, que evidencian cómo NumPy puede ser utilizado para tareas reales en entornos de ciencia de datos y machine learning.

En definitiva, dominar NumPy es un paso imprescindible para cualquier persona que desee trabajar con datos en Python. Su eficiencia, robustez y flexibilidad lo convierten en una de las herramientas más poderosas del ecosistema científico-tecnológico actual.


In [21]:
# Muestra documentación resumida del módulo
np.info(np.ndarray)

 ndarray()

ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object that can be interpreted as a numpy data type.
buffer : object exposing buffer interface, optional
    Used to fill the array with data.
of

## 11. Referencias

Gedefa, T.F., Gouse, G.M., & Iticha, G.T. (2023). Empowering Scientific Computing and Data Manipulation With Numerical Python (NumPy). IGI Global.